/** Inline styles for `IntelModuleView.jsx` (search, loading, analysis panel, raw JSON, recent list). */
export const intelModuleStyles = {
  card: { background: "var(--s1)", border: "1px solid var(--b1)", borderRadius: 10, padding: 20 },
  btn: { padding: "10px 18px", borderRadius: 8, border: "none", background: "var(--ac)", color: "#fff", fontSize: 13, fontWeight: 700, fontFamily: "var(--fd)", cursor: "pointer", letterSpacing: -0.3, transition: "all .15s" },
  srchW: { display: "flex", alignItems: "center", gap: 10, padding: "10px 14px", borderRadius: 10, border: "1px solid var(--b1)", background: "var(--s1)", marginBottom: 14 },
  srchI: { flex: 1, border: "none", background: "none", color: "var(--t1)", fontSize: 13, fontFamily: "var(--fb)", outline: "none" },
  runB: { width: 34, height: 34, borderRadius: 8, border: "none", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", cursor: "pointer", fontSize: 16, fontWeight: 700, flexShrink: 0, transition: "opacity .2s" },
  ldW: { padding: "14px 16px", borderRadius: 10, border: "1px solid var(--b1)", background: "var(--s1)", marginBottom: 14 },
  pTrk: { height: 2, borderRadius: 1, background: "var(--b1)", marginTop: 10, overflow: "hidden" },
  pBar: { height: "100%", borderRadius: 1, animation: "prog 10s ease-out forwards", width: "0%" },
  togB: { background: "none", border: "none", color: "var(--t3)", fontSize: 11, cursor: "pointer", padding: "4px 0", fontFamily: "var(--fb)" },
  rawP: { fontSize: 10, color: "var(--t3)", background: "var(--s2)", borderRadius: 8, padding: 12, overflow: "auto", maxHeight: 180, whiteSpace: "pre-wrap", wordBreak: "break-all", marginTop: 6, border: "1px solid var(--b1)" },
  hItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 12px", borderRadius: 7, background: "var(--s1)", border: "1px solid var(--b1)", marginBottom: 4, cursor: "pointer" },
  analysisSectionLabel: { fontSize: 10, letterSpacing: 2, textTransform: "uppercase", fontWeight: 700, marginBottom: 14 },
  moduleTitle: { fontFamily: "var(--fd)", fontSize: 22, fontWeight: 800, margin: 0, color: "var(--t1)", letterSpacing: -0.5 },
  moduleDesc: { fontSize: 12, color: "var(--t3)", margin: 0 },
  iconWrap: { width: 42, height: 42, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 },
  headerRow: { display: "flex", alignItems: "center", gap: 14, marginBottom: 24 },
  profileGateText: { fontSize: 13, color: "var(--t2)", margin: 0 },
  noteBanner: { marginTop: 8, padding: "8px 14px", borderRadius: 8, background: "rgba(251,191,36,.08)", fontSize: 11, color: "#fbbf24" },
  recentSectionLabel: { fontSize: 10, letterSpacing: 2, color: "var(--t3)", textTransform: "uppercase", marginBottom: 10 },
  recentList: { marginTop: 20 },
  recentQuery: { fontSize: 12, color: "var(--t2)" },
  recentTime: { fontSize: 10, color: "var(--t3)" },
};
